import Head from 'next/head'
import React from 'react';
import { useState } from 'react';
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillInstagram, AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import Image from 'next/legacy/image'
import EuAxel from '../public/EuAxel.jpeg';
import code from '../public/code.png';
import ReactJsText from '../components/ReactJsText';
import JavaScriptText from '../components/JavaScriptText';
import NextJsText from '../components/NextJsText';
import TailwindCSSText from '../components/TailwindCSSText';
import HTMLText from '../components/HTMLText';
import CSSText from '../components/CSSText';
import ToDoList from '../public/ToDoList.png';

export default function Home() {
    const[darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? 'dark': ""}>
      <Head>
        <title>Áxel Vaz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='bg-white px-4 md:px-10 lg:px-20 dark:bg-gray-800 dark:text-white'>
      <section className= 'min-h-screen'>
       <nav className='py-4 flex justify-between border-black dark:border-cyan-500 border-b-2'>
       <h1 className='font-handwritten mt-2 gap-2 text-xl ml-2'>developedbyÁxel</h1>
       <ul className='flex items-center'>
        <li className='cursor-pointer text-xl'><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)}/></li>
        <a href='#resume'><li className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white hover:scale-110 px-4 py-2 rounded-md ml-4'>Resume</li></a>
       </ul>
       </nav>
       <div className='text-center pt-10 pb-6'>
        <h2 className='py-2 text-5xl text-teal-600 font-medium dark:text-cyan-500'>Áxel Vaz</h2>
        <h3 className='py-2 text-3xl'>Front-End Developer</h3>
        <p className='dark:text-white text-gray-800 text-md leading-8'>Brazil</p>
       </div>
        <div className='text-5xl gap-16 flex justify-center pb-2 text-gray-600 dark:text-white'>
        <a href='https://www.instagram.com/axelvazslima/'><AiFillInstagram className='hover:scale-110 hover:text-[#A020F0]' /></a>
        <a href='https://www.linkedin.com/in/axelvaz/'><AiFillLinkedin className='hover:scale-110 hover:text-blue-600' /></a>
        <a href='https://github.com/Axelvazslima/'><AiFillGithub className='hover:scale-110 hover:text-red-500' /></a>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
          <Image src={EuAxel} objectfit='cover' />
        </div>
      </section>

      <section className= 'min-h-screen'>
        <div className='pt-20 pb-10 text-center'>
          <h3 className='text-3xl py-1'>Who Am I?</h3>
          <div className='text-md py-2 leading-8 dark:text-white text-gray-800'>
          <p>My name is Áxel. I am from Brazil and I code apps like a <span className='text-green-800 cursor-pointer'>To-Do List App</span>, API's on github and this website.</p>
          <p>Everything you see here was coded by me using just JavaScript, ReactJs and NextJs. For the design I worked with CSS, it's Library TailwindCSS and obviously HTML.</p>
          <p>I made the decision to pursue this path when I was 17 and studied hard to get into college. Later, while waiting for my college classes to begin, I decided to take matters into my own hands and started taking online courses and watching YouTube videos to continue learning. Additionally, reading Stack Overflow articles and exploring GitHub repositories proved to be extremely helpful in my learning journey.</p>
          <p>Keep scrolling and later on we are diving into these names more deeply and you know what all these strange names do.</p>
          </div>
        </div>
        <div className='py-10 justify-center px-4 rounded-lg shadow-md dark:shadow-cyan-500'>
          <h3 className='dark:text-white text-black text-3xl text-center'>What is coding?</h3>
          <div className='dark:text-white text-gray-800 pt-4'>
          <p>Coding is the process of creating software or applications that can be run on a computer or other device. It involves writing instructions using a programming language, which is a set of rules and syntax that tells the computer what to do. These instructions can range from simple tasks, like displaying text on a screen, to complex processes, like analyzing data and making decisions based on that analysis.</p>
          <p>Coding is a useful skill for many different types of professionals, as it allows them to create programs and applications that can automate tasks, solve problems, and perform a wide variety of other functions. It can be used in fields such as software development, data science, web design, and more. With the right tools and resources, anyone can learn to code and start creating their own programs.</p>
        </div>
        </div>
      </section>
      <section className='min-h-screen'>
        <div className='px-4 mx-4 pt-20 pb-10'>
          <h3 className='py-1 text-3xl text-center pb-8'>Tools I used while building this Web App</h3>
            <div className='group lg:flex w-full pb-12 lg:justify-center lg:gap-16 text-center dark:text-white text-gray-800'>
          <div className='rounded-xl shadow-xl p-2 hover:scale-110 group-hover:opacity-30 transition hover:!opacity-100 hover:shadow-cyan-600  dark:hover:shadow-white'>
            <div className='rounded-full mt-10 cursor-pointer'>
              <JavaScriptText />
            </div>
            <h3 className='text-3xl dark:text-white text-black'>JavaScript</h3>
          </div>
          <div className='rounded-xl shadow-xl hover:shadow-cyan-600 hover:scale-110 group-hover:opacity-30 transition hover:!opacity-100 p-2 dark:hover:shadow-white'>
            <div className='rounded-full mt-10 cursor-pointer'>
            <ReactJsText />
            </div>
          <h3 className='text-3xl dark:text-white text-black '>ReactJs</h3>
          </div>
          <div className='rounded-xl shadow-xl hover:shadow-cyan-600 hover:scale-110 group-hover:opacity-30 transition hover:!opacity-100 dark:hover:shadow-white p-2'>
            <div className='rounded-full mt-10 cursor-pointer'>
              <NextJsText />
            </div>
          <h3 className='text-3xl dark:text-white text-black'>NextJs</h3>
          </div>
          <div className='rounded-xl shadow-xl hover:shadow-cyan-600 hover:scale-110 group-hover:opacity-30 transition hover:!opacity-100 dark:hover:shadow-white p-2'>
            <div className='rounded-full mt-10 cursor-pointer'>
              <HTMLText />
            </div>
          <h3 className='text-3xl dark:text-white text-black'>HTML5</h3>
          </div>
          <div className='rounded-xl shadow-xl hover:shadow-cyan-600 hover:scale-110 group-hover:opacity-30 transition hover:!opacity-100 dark:hover:shadow-white p-2'>
            <div className='rounded-full mt-10 cursor-pointer'>
              <CSSText />
            </div>
          <h3 className='text-3xl dark:text-white text-black'>CSS3</h3>
          </div>
          <div className='rounded-xl shadow-xl hover:shadow-cyan-600 hover:scale-110 group-hover:opacity-30 transition hover:!opacity-100 dark:hover:shadow-white p-2'>
            <div className='rounded-full mt-10 cursor-pointer'>
              <TailwindCSSText />
            </div>
          <h3 className='text-3xl dark:text-white text-black'>TailwindCSS</h3>
          </div>
            </div>
          </div>
        <div className='text-center dark:text-white text-gray-800' id='resume'>
          <h3 className='text-3xl dark:text-white text-black'>Take a look at my Portfolio</h3>
          <p>Since I started learning to code, I have been putting in a lot of work to master this ability.</p>
          <p>So, I decided to compile the most attractive projects in just one place and now you can see my work here.</p>
          <div className='flex justify-center items-center gap-4 py-4 group'>
          <div className='group-hover:opacity-30 transition hover:!opacity-100 rounded-lg shadow-xl hover:shadow-cyan-600 hover:scale-110 dark:hover:shadow-white p-2'><a href='https://github.com/Axelvazslima' target="_blank" rel="noopener noreferrer">
           <Image src={code} width={64} height={64} />
           <h1 className='text-xl dark:text-white text-black'>GitHub</h1>
           <p>My code compilation</p>
          </a></div>
          <div className='group-hover:opacity-30 transition hover:!opacity-100 rounded-lg shadow-xl hover:shadow-cyan-600 hover:scale-110 dark:hover:shadow-white p-2'><a href='#top'>
           <Image src={ToDoList} width={64} height={64} />
           <h1 className='text-xl dark:text-white text-black'>To-Do List</h1>
           <p>JavaScript and ReactJs</p>
           </a></div>
          </div>
        </div>
      </section>
      </main>
      </div>
    
  );
}
